name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B (tests)
        uses: actions/checkout@v3

      - name: Checkout Repo A (Todo App)
        uses: actions/checkout@v3
        with:
          repository: sarang-code2/todo-app
          path: repo-a

      - name: Install Todo App deps
        working-directory: repo-a
        run: npm install

      - name: Start Todo App
        working-directory: repo-a
        run: |
          nohup npm run dev &
          sleep 5

      - name: Install Playwright
        run: npm install && npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test
